#ifndef MESSAGE_TYPES_H
#define MESSAGE_TYPES_H

enum MessageType
{
	MESSAGE_PLAYER_FOUND,
	MESSAGE_RETURN_TO_CARRIER,
	MESSAGE_ATTACK_PLAYER,
	MESSAGE_SEARCH_FOR_PLAYER
};

#endif MESSAGE_TYPES_H