#pragma once

namespace EnemyState
{
	enum 
	{
		CARRIER_APPROACH, 
		CARRIER_APPROACH_CONTACT,
		CARRIER_ATTACK, 
		CARRIER_SEARCH,
		FIGHTER_WANDER, 
		FIGHTER_APPROACH_CARRIER, 
		FIGHTER_APPROACH_TARGET, 
		FIGHTER_ATTACK};
}